import { 
  UserProfile, 
  ScheduleItem, 
  TodayTask, 
  SubjectItem, 
  BookItem, 
  GoalItem, 
  RoadmapPhase,
  BacklogItem,
  StudyEntry,
  PYQItem,
  MCQEntry,
  TestEntry,
  AnswerWritingEntry,
  DiaryEntry
} from '../types';

export const DEFAULT_PROFILE: UserProfile = {
  name: 'Ravi',
  displayName: 'IAS RAVI',
  role: 'UPSC 2029 Aspirant',
  mission: 'First Attempt Preparation',
  tagline: 'चलो कुछ ऐसा कर जाएँ, कि नाम हमारा मिसाल बन जाए।',
  targetYear: 2029,
  firstAttemptYear: 2029,
  jobEndDate: '2026-12-31',
  fullTimeStartDate: '2027-01-01',
  dailyTargetJobHours: 5.5,
  dailyTargetFullTimeHours: 12.0,
  sleepTargetHours: 6.0,
  optionalSubject: 'Political Science & International Relations (PSIR)',
  profilePhoto: null,
  manualModeOverride: 'AUTO',
  pwClassTiming: '19:00 - 22:30 (Live & Recorded)',
};

export const MOTIVATIONAL_QUOTES = [
  'चलो कुछ ऐसा कर जाएँ, कि नाम हमारा मिसाल बन जाए।',
  'एक दिन नहीं — हर दिन।',
  'Consistency beats intensity.',
  'आज की मेहनत, कल की पहचान बनेगी।',
  'Focus on the process, results will follow.',
  'Doubt kills more dreams than failure ever will.',
  'Every revision is a step closer to the LBSNAA gate.',
  'Stay calm, stay hungry, stay disciplined.'
];

export const DEFAULT_JOB_SCHEDULE: ScheduleItem[] = [
  {
    id: 'job-1',
    dayOfWeek: 'all',
    startTime: '05:00',
    endTime: '05:30',
    title: 'Wake Up + Fresh + Hydration',
    durationHours: 0.5,
    category: 'Routine',
    isStudy: false,
    completed: true,
    mode: 'JOB + UPSC',
  },
  {
    id: 'job-2',
    dayOfWeek: 'all',
    startTime: '05:30',
    endTime: '07:00',
    title: '📖 GS Deep Study',
    durationHours: 1.5,
    category: 'GS',
    isStudy: true,
    completed: true,
    mode: 'JOB + UPSC',
    notes: 'Polity / Modern History core concept consolidation',
  },
  {
    id: 'job-3',
    dayOfWeek: 'all',
    startTime: '07:00',
    endTime: '08:00',
    title: 'Ready + Healthy Breakfast',
    durationHours: 1.0,
    category: 'Routine',
    isStudy: false,
    completed: true,
    mode: 'JOB + UPSC',
  },
  {
    id: 'job-4',
    dayOfWeek: 'all',
    startTime: '08:00',
    endTime: '09:00',
    title: 'Travel + The Hindu / Indian Express Current Affairs',
    durationHours: 0.5,
    category: 'Current Affairs',
    isStudy: true,
    completed: true,
    mode: 'JOB + UPSC',
    notes: 'Reading editorial analysis on mobile/tablet during commute',
  },
  {
    id: 'job-5',
    dayOfWeek: 'all',
    startTime: '09:00',
    endTime: '18:00',
    title: '💼 Professional Job Duties + Lunch Break',
    durationHours: 9.0,
    category: 'Job',
    isStudy: false,
    completed: false,
    mode: 'JOB + UPSC',
  },
  {
    id: 'job-6',
    dayOfWeek: 'all',
    startTime: '18:00',
    endTime: '19:00',
    title: 'Travel Back + Fresh + Light Dinner',
    durationHours: 1.0,
    category: 'Routine',
    isStudy: false,
    completed: false,
    mode: 'JOB + UPSC',
  },
  {
    id: 'job-7',
    dayOfWeek: 'all',
    startTime: '19:00',
    endTime: '20:30',
    title: '🎓 PW Live Class',
    durationHours: 1.5,
    category: 'PW Class',
    isStudy: true,
    completed: false,
    mode: 'JOB + UPSC',
    notes: 'PhysicsWallah UPSC Batch Live Session with active notes',
  },
  {
    id: 'job-8',
    dayOfWeek: 'all',
    startTime: '20:30',
    endTime: '21:00',
    title: 'Dinner / Mindful Break',
    durationHours: 0.5,
    category: 'Break',
    isStudy: false,
    completed: false,
    mode: 'JOB + UPSC',
  },
  {
    id: 'job-9',
    dayOfWeek: 'all',
    startTime: '21:00',
    endTime: '22:30',
    title: '🎓 PW Recorded Class / Topic Deep Dive',
    durationHours: 1.5,
    category: 'PW Class',
    isStudy: true,
    completed: false,
    mode: 'JOB + UPSC',
    notes: 'Lecture coverage at 1.25x speed with structured mindmaps',
  },
  {
    id: 'job-10',
    dayOfWeek: 'all',
    startTime: '22:30',
    endTime: '23:00',
    title: '📓 Diary + Next-Day Planning',
    durationHours: 0.5,
    category: 'Diary',
    isStudy: true,
    completed: false,
    mode: 'JOB + UPSC',
    notes: 'Fill daily register, review progress, set tomorrow morning targets',
  },
  {
    id: 'job-11',
    dayOfWeek: 'all',
    startTime: '23:00',
    endTime: '05:00',
    title: '😴 Deep Restorative Sleep (6 hrs)',
    durationHours: 6.0,
    category: 'Sleep',
    isStudy: false,
    completed: false,
    mode: 'JOB + UPSC',
  },
];

export const DEFAULT_FULLTIME_SCHEDULE: ScheduleItem[] = [
  {
    id: 'ft-1',
    dayOfWeek: 'all',
    startTime: '05:30',
    endTime: '07:30',
    title: 'GS Core Subject (Deep Session 1)',
    durationHours: 2.0,
    category: 'GS',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
    notes: 'High concentration slot for heavyweight conceptual clarity',
  },
  {
    id: 'ft-2',
    dayOfWeek: 'all',
    startTime: '07:30',
    endTime: '08:00',
    title: 'Nutritious Breakfast + Fresh',
    durationHours: 0.5,
    category: 'Routine',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-3',
    dayOfWeek: 'all',
    startTime: '08:00',
    endTime: '09:30',
    title: 'GS / NCERT Textbooks',
    durationHours: 1.5,
    category: 'NCERT',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
    notes: 'Line-by-line NCERT chapter mastery with margin notes',
  },
  {
    id: 'ft-4',
    dayOfWeek: 'all',
    startTime: '09:30',
    endTime: '10:00',
    title: 'Hydration & Mind Walk Break',
    durationHours: 0.5,
    category: 'Break',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-5',
    dayOfWeek: 'all',
    startTime: '10:00',
    endTime: '11:30',
    title: 'Optional Subject (PSIR / Paper 1 & 2)',
    durationHours: 1.5,
    category: 'Optional',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
    notes: 'Western Political Thought / Indian Political Thought & IR',
  },
  {
    id: 'ft-6',
    dayOfWeek: 'all',
    startTime: '11:30',
    endTime: '12:30',
    title: 'Active Revision & Micro-Notes Synthesis',
    durationHours: 1.0,
    category: 'Revision',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-7',
    dayOfWeek: 'all',
    startTime: '12:30',
    endTime: '13:30',
    title: 'Lunch + Power Nap / Rest',
    durationHours: 1.0,
    category: 'Routine',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-8',
    dayOfWeek: 'all',
    startTime: '13:30',
    endTime: '15:00',
    title: 'Current Affairs & Editorial Synthesis',
    durationHours: 1.5,
    category: 'Current Affairs',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-9',
    dayOfWeek: 'all',
    startTime: '15:00',
    endTime: '15:30',
    title: 'Evening Tea / Brain Refresh',
    durationHours: 0.5,
    category: 'Break',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-10',
    dayOfWeek: 'all',
    startTime: '15:30',
    endTime: '17:00',
    title: 'MCQs / PYQs / Daily Mains Answer Writing',
    durationHours: 1.5,
    category: 'Answer Writing',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
    notes: '2 Mains questions writing under strict 9-minute clock timer + 25 MCQs',
  },
  {
    id: 'ft-11',
    dayOfWeek: 'all',
    startTime: '17:00',
    endTime: '18:30',
    title: 'PW UPSC Class Session 1',
    durationHours: 1.5,
    category: 'PW Class',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-12',
    dayOfWeek: 'all',
    startTime: '18:30',
    endTime: '19:00',
    title: 'Active Stretch & Break',
    durationHours: 0.5,
    category: 'Break',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-13',
    dayOfWeek: 'all',
    startTime: '19:00',
    endTime: '20:30',
    title: 'PW UPSC Class Session 2',
    durationHours: 1.5,
    category: 'PW Class',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-14',
    dayOfWeek: 'all',
    startTime: '20:30',
    endTime: '21:00',
    title: 'Dinner & Family Time',
    durationHours: 0.5,
    category: 'Break',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-15',
    dayOfWeek: 'all',
    startTime: '21:00',
    endTime: '22:00',
    title: 'Class Revision + Topic PYQ Drills',
    durationHours: 1.0,
    category: 'Revision',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-16',
    dayOfWeek: 'all',
    startTime: '22:00',
    endTime: '22:30',
    title: 'Daily Diary + Next-Day Master Plan',
    durationHours: 0.5,
    category: 'Diary',
    isStudy: true,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
  {
    id: 'ft-17',
    dayOfWeek: 'all',
    startTime: '22:30',
    endTime: '05:30',
    title: '😴 Restorative Sleep (7 hrs)',
    durationHours: 7.0,
    category: 'Sleep',
    isStudy: false,
    completed: false,
    mode: 'FULL-TIME UPSC',
  },
];

export const DEFAULT_TODAY_TASKS: TodayTask[] = [
  {
    id: 'task-1',
    date: '2026-09-16',
    title: 'GS Deep Study — Indian Polity (Preamble & Fundamental Rights)',
    durationHours: 1.5,
    category: 'GS',
    completed: true,
    order: 1,
    notes: 'Covered Article 12-18 and Laxmikanth Chapter 7 notes'
  },
  {
    id: 'task-2',
    date: '2026-09-16',
    title: 'Current Affairs — The Hindu Editorial & Monthly Compendium',
    durationHours: 0.5,
    category: 'Current Affairs',
    completed: true,
    order: 2,
    notes: 'SCO summit outcomes and Green Hydrogen Mission updates'
  },
  {
    id: 'task-3',
    date: '2026-09-16',
    title: 'PW Live Class — Modern Indian History (Tribal & Peasant Movements)',
    durationHours: 1.5,
    category: 'PW Class',
    completed: false,
    order: 3,
    notes: 'PhysicsWallah evening live stream at 19:00'
  },
  {
    id: 'task-4',
    date: '2026-09-16',
    title: 'PW Recorded Class — Geography Physical Landscapes & Geomorphology',
    durationHours: 1.5,
    category: 'PW Class',
    completed: false,
    order: 4,
    notes: 'Class 11 Physical Geography plate tectonics module'
  },
  {
    id: 'task-5',
    date: '2026-09-16',
    title: 'Diary + Tomorrow Planning + Micro-Revision',
    durationHours: 0.5,
    category: 'Diary',
    completed: false,
    order: 5,
    notes: 'Log daily study register and assess backlog'
  }
];

export const DEFAULT_SUBJECTS: SubjectItem[] = [
  {
    id: 'sub-polity',
    name: 'Indian Polity & Constitution',
    category: 'GS',
    studyHours: 78.5,
    totalTopics: 62,
    completedTopics: 28,
    revisionCount: 3,
    pyqCount: 140,
    mcqCount: 380,
    testCount: 4,
    color: '#4F46E5', // Indigo
    description: 'GS Paper II: Preamble, Fundamental Rights, DPSP, Parliament, Judiciary & Constitutional Bodies'
  },
  {
    id: 'sub-history',
    name: 'History & Indian Culture',
    category: 'GS',
    studyHours: 64.0,
    totalTopics: 55,
    completedTopics: 22,
    revisionCount: 2,
    pyqCount: 110,
    mcqCount: 260,
    testCount: 3,
    color: '#D97706', // Amber
    description: 'GS Paper I: Ancient, Medieval, Modern Freedom Struggle & Art & Culture'
  },
  {
    id: 'sub-geography',
    name: 'Geography & Environment',
    category: 'GS',
    studyHours: 52.0,
    totalTopics: 48,
    completedTopics: 19,
    revisionCount: 2,
    pyqCount: 95,
    mcqCount: 210,
    testCount: 2,
    color: '#059669', // Emerald
    description: 'GS Paper I & III: Physical, Economic, Human Geography, Biodiversity & Climate Change'
  },
  {
    id: 'sub-economy',
    name: 'Indian Economy & Development',
    category: 'GS',
    studyHours: 46.5,
    totalTopics: 44,
    completedTopics: 15,
    revisionCount: 1,
    pyqCount: 80,
    mcqCount: 190,
    testCount: 2,
    color: '#2563EB', // Blue
    description: 'GS Paper III: Macroeconomics, Budgeting, Inclusive Growth, Agriculture & Infrastructure'
  },
  {
    id: 'sub-environment',
    name: 'Environment & Ecology',
    category: 'GS',
    studyHours: 34.0,
    totalTopics: 32,
    completedTopics: 12,
    revisionCount: 1,
    pyqCount: 65,
    mcqCount: 150,
    testCount: 2,
    color: '#10B981', // Teal
    description: 'GS Paper III: Wildlife Protection, UNFCCC Conventions, National Parks, Pollution Control'
  },
  {
    id: 'sub-scitech',
    name: 'Science & Technology',
    category: 'GS',
    studyHours: 28.0,
    totalTopics: 26,
    completedTopics: 10,
    revisionCount: 1,
    pyqCount: 45,
    mcqCount: 120,
    testCount: 1,
    color: '#7C3AED', // Purple
    description: 'GS Paper III: Space, Biotechnology, AI, Defense Tech, Nanotechnology, Nuclear policy'
  },
  {
    id: 'sub-governance',
    name: 'Governance & Social Justice',
    category: 'GS',
    studyHours: 22.0,
    totalTopics: 24,
    completedTopics: 7,
    revisionCount: 1,
    pyqCount: 30,
    mcqCount: 80,
    testCount: 1,
    color: '#0891B2', // Cyan
    description: 'GS Paper II: Government policies, Welfare schemes, Health, Education, Human resources'
  },
  {
    id: 'sub-society',
    name: 'Indian Society',
    category: 'GS',
    studyHours: 18.0,
    totalTopics: 18,
    completedTopics: 6,
    revisionCount: 1,
    pyqCount: 25,
    mcqCount: 50,
    testCount: 1,
    color: '#E11D48', // Rose
    description: 'GS Paper I: Salient features, Diversity, Role of women, Urbanization, Globalization'
  },
  {
    id: 'sub-ir',
    name: 'International Relations',
    category: 'GS',
    studyHours: 26.0,
    totalTopics: 28,
    completedTopics: 9,
    revisionCount: 1,
    pyqCount: 35,
    mcqCount: 75,
    testCount: 1,
    color: '#6366F1', // Indigo Accent
    description: 'GS Paper II: India and its neighborhood, Bilateral groupings, Global institutions (UN, WTO)'
  },
  {
    id: 'sub-ethics',
    name: 'Ethics, Integrity & Aptitude',
    category: 'GS',
    studyHours: 20.0,
    totalTopics: 30,
    completedTopics: 5,
    revisionCount: 0,
    pyqCount: 20,
    mcqCount: 40,
    testCount: 1,
    color: '#9333EA', // Purple
    description: 'GS Paper IV: Ethics in Public Administration, Human Values, Emotional Intelligence, Case Studies'
  },
  {
    id: 'sub-optional',
    name: 'PSIR Optional (Paper 1 & 2)',
    category: 'Optional',
    studyHours: 42.0,
    totalTopics: 50,
    completedTopics: 14,
    revisionCount: 1,
    pyqCount: 55,
    mcqCount: 0,
    testCount: 2,
    color: '#8B5CF6', // Violet
    description: 'Political Theory, Indian Political Thought, Indian Nationalism, Global Politics & Foreign Policy'
  },
  {
    id: 'sub-currentaffairs',
    name: 'Current Affairs & Editorials',
    category: 'Other',
    studyHours: 58.0,
    totalTopics: 120,
    completedTopics: 65,
    revisionCount: 5,
    pyqCount: 90,
    mcqCount: 320,
    testCount: 6,
    color: '#EC4899', // Pink
    description: 'Daily The Hindu / IE, PIB Summaries, PW Monthly Current Affairs Compendiums'
  },
  {
    id: 'sub-csat',
    name: 'CSAT (Paper II Prelims)',
    category: 'Other',
    studyHours: 16.0,
    totalTopics: 20,
    completedTopics: 6,
    revisionCount: 1,
    pyqCount: 40,
    mcqCount: 110,
    testCount: 1,
    color: '#F59E0B', // Amber
    description: 'Reading Comprehension, Quantitative Aptitude, Logical Reasoning & Data Interpretation'
  },
  {
    id: 'sub-essay',
    name: 'Mains Essay Writing',
    category: 'Other',
    studyHours: 14.0,
    totalTopics: 15,
    completedTopics: 4,
    revisionCount: 1,
    pyqCount: 15,
    mcqCount: 0,
    testCount: 1,
    color: '#14B8A6', // Teal
    description: 'Philosophical essays, Socio-economic topics, Governance and Global themes structure'
  }
];

export const DEFAULT_BOOKS: BookItem[] = [
  {
    id: 'book-1',
    name: 'Indian Polity (7th Edition)',
    subject: 'Indian Polity & Constitution',
    author: 'M. Laxmikanth',
    type: 'Standard Book',
    totalPages: 850,
    completedPages: 380,
    progressPercent: 45,
    status: 'Reading',
    notes: 'The Bible for Polity. Core focus on Fundamental Rights, Parliament, and Constitutional Bodies.'
  },
  {
    id: 'book-2',
    name: 'A Brief History of Modern India',
    subject: 'History & Indian Culture',
    author: 'Rajiv Ahir (Spectrum)',
    type: 'Standard Book',
    totalPages: 680,
    completedPages: 290,
    progressPercent: 43,
    status: 'Reading',
    notes: 'Chapters on 1857 Revolt, INC formation, Swadeshi and Gandhian Phases revised twice.'
  },
  {
    id: 'book-3',
    name: 'Class 11 NCERT: Indian Constitution at Work',
    subject: 'Indian Polity & Constitution',
    author: 'NCERT',
    type: 'NCERT',
    totalPages: 240,
    completedPages: 240,
    progressPercent: 100,
    status: 'Revision 2',
    notes: 'Completed with comprehensive handwritten margin notes.'
  },
  {
    id: 'book-4',
    name: 'Class 11 NCERT: Fundamentals of Physical Geography',
    subject: 'Geography & Environment',
    author: 'NCERT',
    type: 'NCERT',
    totalPages: 160,
    completedPages: 160,
    progressPercent: 100,
    status: 'Completed',
    notes: 'Crucial for understanding plate tectonics, climatology, and ocean currents.'
  },
  {
    id: 'book-5',
    name: 'Class 11 NCERT: An Introduction to Indian Art',
    subject: 'History & Indian Culture',
    author: 'NCERT',
    type: 'NCERT',
    totalPages: 140,
    completedPages: 110,
    progressPercent: 78,
    status: 'Reading',
    notes: 'Temple architecture styles (Nagara, Dravida, Vesara) and Indus Valley iconography.'
  },
  {
    id: 'book-6',
    name: 'Indian Economy (15th Edition)',
    subject: 'Indian Economy & Development',
    author: 'Ramesh Singh / Nitin Singhania',
    type: 'Standard Book',
    totalPages: 720,
    completedPages: 180,
    progressPercent: 25,
    status: 'Reading',
    notes: 'Completed national income accounting and monetary policy chapters.'
  },
  {
    id: 'book-7',
    name: 'Environment (9th Edition)',
    subject: 'Environment & Ecology',
    author: 'Shankar IAS Academy',
    type: 'Standard Book',
    totalPages: 450,
    completedPages: 140,
    progressPercent: 31,
    status: 'Reading',
    notes: 'Ecosystem dynamics, Biodiversity conventions, and Ramsar wetland sites.'
  },
  {
    id: 'book-8',
    name: 'PhysicsWallah UPSC Foundation GS Modules',
    subject: 'All GS Papers',
    author: 'PW OnlyIAS Faculty',
    type: 'PW Material',
    totalPages: 900,
    completedPages: 360,
    progressPercent: 40,
    status: 'Reading',
    notes: 'Comprehensive lecture handouts with integrated PYQ analysis.'
  },
  {
    id: 'book-9',
    name: 'Certificate Physical and Human Geography',
    subject: 'Geography & Environment',
    author: 'G.C. Leong',
    type: 'Reference',
    totalPages: 210,
    completedPages: 90,
    progressPercent: 42,
    status: 'Reading',
    notes: 'Weather and Climatic Zones portion is essential for Prelims.'
  }
];

export const DEFAULT_GOALS: GoalItem[] = [
  {
    id: 'goal-1',
    title: 'Complete Class 6-12 NCERT Foundation across all GS Subjects',
    category: 'NCERT',
    deadline: '2026-11-30',
    progressPercent: 72,
    status: 'In Progress',
    notes: 'History & Geography 80% done; Economics & Polity completed.'
  },
  {
    id: 'goal-2',
    title: 'Finish Laxmikanth Indian Polity first complete reading + margin notes',
    category: 'Polity',
    deadline: '2026-10-31',
    progressPercent: 55,
    status: 'In Progress',
    notes: 'Targeting Chapter 1 to 35 before end of October.'
  },
  {
    id: 'goal-3',
    title: 'Complete PW GS Foundation Live Batch 2026 Semester 1',
    category: 'PW Module',
    deadline: '2026-12-31',
    progressPercent: 48,
    status: 'In Progress',
    notes: 'Maintain zero live class backlog while managing day job.'
  },
  {
    id: 'goal-4',
    title: 'Solve 500 Prelims PYQs with detailed explanations and error journal',
    category: 'PYQs',
    deadline: '2026-12-15',
    progressPercent: 62,
    status: 'In Progress',
    notes: '310 solved so far with 74% average accuracy.'
  },
  {
    id: 'goal-5',
    title: 'Write 100 GS Mains practice answers under timed conditions',
    category: 'Answer Writing',
    deadline: '2027-04-30',
    progressPercent: 28,
    status: 'In Progress',
    notes: '28 answers submitted; focused on introduction-body-conclusion format.'
  },
  {
    id: 'goal-6',
    title: 'Complete PSIR Optional Paper 1 Political Theory basic syllabus',
    category: 'Optional',
    deadline: '2027-03-31',
    progressPercent: 20,
    status: 'Not Started',
    notes: 'Scheduled for deeper study once full-time mode begins in Jan 2027.'
  }
];

export const DEFAULT_ROADMAP_PHASES: RoadmapPhase[] = [
  {
    id: 'phase-2026',
    year: 2026,
    title: 'Phase 1: Foundation & NCERT Base',
    phaseName: 'FOUNDATION',
    subtitle: 'Building Habits, Discipline & NCERT Base (Job + UPSC Mode)',
    focus: 'NCERTs, Core Fundamentals & Study Discipline (5.5 hrs/day)',
    timeframe: 'Jan 2026 – Dec 2026',
    status: 'ACTIVE',
    progressPercent: 68,
    isCurrent: true,
    focusPoints: [
      'NCERT basics across History, Geography, Polity, Science & Economy',
      'Basic GS understanding and conceptual mapping',
      'Current Affairs daily reading habit via The Hindu / IE',
      'PW UPSC Foundation batch integration',
      'Daily 5.5 hours discipline around full-time job schedule',
      'Basic consolidated handwritten & digital micro-notes',
      'PYQ introduction: understanding UPSC question trends (2013-2025)',
      'Consistent 90%+ daily study streak'
    ],
    goals: [
      'Finish NCERTs (Polity & Geography Class 11-12)',
      'Establish 5.5 hrs daily study rhythm with job',
      'Complete 300 Prelims PYQs',
      'First round reading of Spectrum Modern India',
      'Transition preparation for Full-Time Mode on 1 Jan 2027'
    ],
    keyBooks: [
      'NCERT Class 11-12 (Polity & Geo)',
      'M. Laxmikanth (Polity)',
      'Spectrum (Modern History)',
      'PW Foundation Modules'
    ],
    milestones: [
      { id: 'm-26-1', title: 'Finish NCERTs (Polity & Geography Class 11-12)', completed: true },
      { id: 'm-26-2', title: 'Establish 5.5 hrs daily study rhythm with job', completed: true },
      { id: 'm-26-3', title: 'Complete 300 Prelims PYQs', completed: true },
      { id: 'm-26-4', title: 'First round reading of Spectrum Modern India', completed: false },
      { id: 'm-26-5', title: 'Transition preparation for Full-Time Mode on 1 Jan 2027', completed: false }
    ],
    notes: 'Crucial year to build the stamina and foundation without burning out at job.'
  },
  {
    id: 'phase-2027',
    year: 2027,
    title: 'Phase 2: Full-Time Acceleration & Advanced GS',
    phaseName: 'CORE GS + NCERT + STANDARD BOOKS',
    subtitle: 'Full-Time Immersion: Standard Textbooks, Optional & Revision System',
    focus: 'Full-Time Mode (12 hrs/day), Standard Books & PSIR Optional',
    timeframe: 'Jan 2027 – Dec 2027',
    status: 'UPCOMING',
    progressPercent: 0,
    isCurrent: false,
    focusPoints: [
      'Full-time 12.0 hours daily preparation mode kickoff on 1 January 2027',
      'Deep mastery of standard references: Laxmikanth, Spectrum, Ramesh Singh, Shankar IAS',
      'Complete remaining NCERTs and thematic synthesis',
      'PSIR Optional development (Paper 1 & Paper 2 core theory)',
      'Regular daily answer writing drills (2 questions/day)',
      'Structured 1-7-30 days spaced revision system',
      'Advanced Current Affairs integration with Mains syllabus keywords',
      'Quarterly sectional tests with in-depth mistake analysis'
    ],
    goals: [
      'Launch 12 hrs/day Full-Time Mode on Jan 1',
      'Complete Laxmikanth 2nd Revision',
      'Complete PSIR Paper 1 syllabus',
      'Write 200 Mains Answers with peer/mentor evaluation',
      'Solve 1,500 MCQs with 75%+ accuracy'
    ],
    keyBooks: [
      'Ramesh Singh (Economy)',
      'Shankar IAS (Environment)',
      'PSIR Optional Paper 1 & 2',
      'Laxmikanth 2nd Revision'
    ],
    milestones: [
      { id: 'm-27-1', title: 'Launch 12 hrs/day Full-Time Mode on Jan 1', completed: false },
      { id: 'm-27-2', title: 'Complete Laxmikanth 2nd Revision', completed: false },
      { id: 'm-27-3', title: 'Complete PSIR Paper 1 syllabus', completed: false },
      { id: 'm-27-4', title: 'Write 200 Mains Answers with peer/mentor evaluation', completed: false },
      { id: 'm-27-5', title: 'Solve 1,500 MCQs with 75%+ accuracy', completed: false }
    ],
    notes: 'The engine room year: Maximum dedicated hours, deep focus, and zero workplace distractions.'
  },
  {
    id: 'phase-2028',
    year: 2028,
    title: 'Phase 3: Intensive Mock Tests & Answer Writing',
    phaseName: 'ADVANCED PREPARATION + ANSWER WRITING + TESTS',
    subtitle: 'Mains & Prelims Test Series, CSAT Mastery & Rigorous Revision',
    focus: 'Full-Length Test Series, Answer Writing Drills & 3x Revision',
    timeframe: 'Jan 2028 – Dec 2028',
    status: 'PLANNED',
    progressPercent: 0,
    isCurrent: false,
    focusPoints: [
      'Advanced GS micro-topics, Ethics case studies, and Governance frameworks',
      'Complete PSIR Optional syllabus and answer writing consolidation',
      'Full-length Prelims Test Series (35+ full mock tests)',
      'Full-length Mains Test Series with strict 3-hour exam simulations',
      'Mains Essay structured framework and quote repository',
      'CSAT targeted practice and score stabilization above 110+',
      'Intensive 3-cycle revision before the final exam year'
    ],
    goals: [
      'Complete 30 Full Prelims Mock Tests',
      'Write 12 Full-Length Mains GS papers',
      'PSIR Optional Complete Revision 3x',
      'CSAT mock test score consistently 110+'
    ],
    keyBooks: [
      'Vision IAS / Forum IAS Mock Series',
      'Ethics Lexicon & Case Studies',
      'CSAT Quantitative Aptitude',
      'Consolidated Hand Micro-Notes'
    ],
    milestones: [
      { id: 'm-28-1', title: 'Complete 30 Full Prelims Mock Tests', completed: false },
      { id: 'm-28-2', title: 'Write 12 Full-Length Mains GS papers', completed: false },
      { id: 'm-28-3', title: 'PSIR Optional Complete Revision 3x', completed: false },
      { id: 'm-28-4', title: 'CSAT mock test score consistently 110+', completed: false }
    ],
    notes: 'Polishing test temperament, speed, time management, and answer presentation.'
  },
  {
    id: 'phase-2029',
    year: 2029,
    title: 'Phase 4: UPSC CSE 2029 Exam Year & AIR Top 50',
    phaseName: 'ATTEMPT & TRIUMPH',
    subtitle: 'UPSC CSE 2029 — First Attempt Victory Mission',
    focus: 'Prelims, Mains, Interview & LBSNAA Calling',
    timeframe: 'Jan 2029 – May 2029 (Prelims) & Sep 2029 (Mains)',
    status: 'TARGET',
    progressPercent: 0,
    isCurrent: false,
    focusPoints: [
      'Prelims Mission Mode (January to May 2029): High-speed mock tests, budget, survey, map-based questions',
      'Prelims Exam Execution with composed calm temperament',
      'Mains Mission Mode (June to September 2029): Daily 3-hour writing blocks, essay, ethics case studies',
      'Mains Exam Execution: 9 papers with peak physical and mental energy',
      'Interview / Personality Test Preparation (October to December 2029)',
      'Final Rank in Top 50 — Entering LBSNAA'
    ],
    goals: [
      'UPSC Prelims 2029 Exam Cleared with 110+ cutoff safety',
      'UPSC Mains 2029 All 9 Papers executed with mastery',
      'UPSC Interview Board Interaction with confidence',
      'Final Merit List: IAS Selection Confirmed 🇮🇳'
    ],
    keyBooks: [
      'Union Budget & Economic Survey 2029',
      'Yearly Current Affairs Compilations',
      'PYQ 2013-2028 Final Flashcards'
    ],
    milestones: [
      { id: 'm-29-1', title: 'UPSC Prelims 2029 Exam Cleared with 110+ cutoff safety', completed: false },
      { id: 'm-29-2', title: 'UPSC Mains 2029 All 9 Papers executed with mastery', completed: false },
      { id: 'm-29-3', title: 'UPSC Interview Board Interaction', completed: false },
      { id: 'm-29-4', title: 'Final Merit List: IAS Selection Confirmed 🇮🇳', completed: false }
    ],
    notes: 'The culmination of all tears, sweat, early mornings, and sacrifices.'
  }
];

export const DEFAULT_BACKLOG: BacklogItem[] = [
  {
    id: 'backlog-1',
    task: 'PW Ancient History Lecture #14 (Mauryan Administration & Ashokan Inscriptions)',
    topic: 'PW Ancient History Lecture #14 (Mauryan Administration & Ashokan Inscriptions)',
    subject: 'History & Culture',
    reason: 'Missed due to late office meeting on Tuesday evening. Need to cover at 1.5x speed.',
    category: 'Missed Lecture',
    priority: 'High',
    plannedDate: '2026-09-18',
    missedDate: '2026-09-15',
    deadline: '2026-09-18',
    status: 'Pending',
    cleared: false,
    notes: 'Missed due to late office meeting on Tuesday evening. Need to cover at 1.5x speed.',
    createdAt: '2026-09-15'
  },
  {
    id: 'backlog-2',
    task: 'Geography NCERT Chapter 5: Minerals and Rocks detailed summary notes',
    topic: 'Geography NCERT Chapter 5: Minerals and Rocks detailed summary notes',
    subject: 'Geography',
    reason: 'Chapter read, but rock cycle diagram and classification chart pending.',
    category: 'Pending Topic',
    priority: 'Medium',
    plannedDate: '2026-09-20',
    missedDate: '2026-09-14',
    deadline: '2026-09-20',
    status: 'In Progress',
    cleared: false,
    notes: 'Chapter read, but rock cycle diagram and classification chart pending.',
    createdAt: '2026-09-14'
  },
  {
    id: 'backlog-3',
    task: 'Weekly Current Affairs Revision (1st Week September 2026)',
    topic: 'Weekly Current Affairs Revision (1st Week September 2026)',
    subject: 'Current Affairs',
    reason: 'Consolidate bilateral summits and Supreme Court constitutional bench rulings.',
    category: 'Pending Revision',
    priority: 'High',
    plannedDate: '2026-09-19',
    missedDate: '2026-09-12',
    deadline: '2026-09-19',
    status: 'Pending',
    cleared: false,
    notes: 'Consolidate bilateral summits and Supreme Court constitutional bench rulings.',
    createdAt: '2026-09-12'
  }
];

export const DEFAULT_STUDY_ENTRIES: StudyEntry[] = [
  {
    id: 'entry-1',
    date: '2026-09-16',
    subject: 'Indian Polity & Constitution',
    topic: 'Fundamental Rights (Article 14 to 18) & Right to Equality',
    studyType: 'GS',
    startTime: '05:30',
    endTime: '07:00',
    durationHours: 1.5,
    source: 'M. Laxmikanth + Bare Act',
    book: 'Indian Polity (7th Edition)',
    revision: false,
    mcqCount: 20,
    pyqCount: 10,
    answerWritingCount: 0,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Moderate',
    notes: 'Focused on doctrine of reasonable classification and arbitrary state action under Art 14.',
    createdAt: '2026-09-16T07:05:00Z'
  },
  {
    id: 'entry-2',
    date: '2026-09-16',
    subject: 'Current Affairs & Editorials',
    topic: 'India-Middle East-Europe Economic Corridor (IMEC) Progress',
    studyType: 'Current Affairs',
    startTime: '08:15',
    endTime: '08:45',
    durationHours: 0.5,
    source: 'The Hindu & Indian Express',
    revision: false,
    mcqCount: 5,
    pyqCount: 0,
    answerWritingCount: 0,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Easy',
    notes: 'Analyzed strategic implications for maritime transit and trade balance.',
    createdAt: '2026-09-16T08:50:00Z'
  },
  {
    id: 'entry-3',
    date: '2026-09-15',
    subject: 'History & Indian Culture',
    topic: 'Socio-Religious Reform Movements (Brahmo Samaj & Arya Samaj)',
    studyType: 'Standard Book',
    startTime: '05:30',
    endTime: '07:00',
    durationHours: 1.5,
    source: 'Spectrum Modern India',
    book: 'A Brief History of Modern India',
    revision: true,
    mcqCount: 25,
    pyqCount: 15,
    answerWritingCount: 1,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Moderate',
    notes: 'Raja Ram Mohan Roy contributions, press freedom and women emancipation legislation.',
    createdAt: '2026-09-15T07:10:00Z'
  },
  {
    id: 'entry-4',
    date: '2026-09-15',
    subject: 'PhysicsWallah GS Foundation',
    topic: 'Physical Geography: Atmospheric Circulation & Pressure Belts',
    studyType: 'PW Class',
    startTime: '19:00',
    endTime: '22:00',
    durationHours: 3.0,
    source: 'PW Live & Recorded Class',
    lecture: 'Geography Module Lecture 18',
    revision: false,
    mcqCount: 15,
    pyqCount: 8,
    answerWritingCount: 0,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Moderate',
    notes: 'Hadley, Ferrel, and Polar cells dynamics with Coriolis force effects.',
    createdAt: '2026-09-15T22:15:00Z'
  },
  {
    id: 'entry-5',
    date: '2026-09-14',
    subject: 'Indian Polity & Constitution',
    topic: 'Preamble, Salient Features & Basic Structure Doctrine',
    studyType: 'Revision',
    startTime: '05:30',
    endTime: '07:00',
    durationHours: 1.5,
    source: 'Handwritten Notes & Laxmikanth Ch 3-4',
    revision: true,
    mcqCount: 30,
    pyqCount: 12,
    answerWritingCount: 1,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Easy',
    notes: 'Kesavananda Bharati case 1973 13-judge bench analysis.',
    createdAt: '2026-09-14T07:05:00Z'
  },
  {
    id: 'entry-6',
    date: '2026-09-14',
    subject: 'PW Live Class',
    topic: 'Modern History: British Expansion and Subsidiary Alliance',
    studyType: 'PW Class',
    startTime: '19:00',
    endTime: '22:30',
    durationHours: 3.5,
    source: 'PW OnlyIAS',
    lecture: 'Modern History Session 12',
    revision: false,
    mcqCount: 20,
    pyqCount: 5,
    answerWritingCount: 0,
    testCount: 0,
    status: 'Completed',
    difficulty: 'Moderate',
    notes: 'Lord Wellesley policies, Anglo-Mysore and Anglo-Maratha wars sequence.',
    createdAt: '2026-09-14T22:35:00Z'
  },
  {
    id: 'entry-7',
    date: '2026-09-13',
    subject: 'Indian Economy & Development',
    topic: 'Monetary Policy Framework, RBI Repo Rate & Inflation Targeting',
    studyType: 'GS',
    startTime: '06:00',
    endTime: '11:30',
    durationHours: 5.5,
    source: 'Ramesh Singh + Economic Survey',
    revision: false,
    mcqCount: 40,
    pyqCount: 18,
    answerWritingCount: 2,
    testCount: 1,
    status: 'Completed',
    difficulty: 'Hard',
    notes: 'Sunday deep marathon study session! Covered MPC framework and core vs headline CPI.',
    createdAt: '2026-09-13T12:00:00Z'
  }
];

export const DEFAULT_PYQS: PYQItem[] = [
  {
    id: 'pyq-1',
    year: 2023,
    exam: 'Prelims',
    subject: 'Indian Polity & Constitution',
    topic: 'Due Process of Law vs Procedure Established by Law',
    question: 'In India, what is the exact implication of the "Due Process of Law"? (A) The procedure established by law (B) An impartial and independent judiciary (C) Fair and reasonable application of law (D) Equality before law',
    attempted: true,
    correct: true,
    explanation: 'Due Process of Law encompasses both procedural fairness and substantive fairness (natural justice), established firmly in Maneka Gandhi vs UOI (1978). Correct option is (C).',
    revisionRequired: false,
    createdAt: '2026-09-10'
  },
  {
    id: 'pyq-2',
    year: 2022,
    exam: 'Prelims',
    subject: 'Environment & Ecology',
    topic: 'Wetlands Conservation',
    question: 'Consider the following pairs of Wetlands and Confluence of Rivers: 1. Harike Wetlands: Confluence of Beas and Satluj, 2. Keoladeo Ghana: Confluence of Banas and Chambal, 3. Kolleru Lake: Confluence of Musi and Krishna. Which pairs are correctly matched?',
    attempted: true,
    correct: false,
    explanation: 'Only Pair 1 is correct. Keoladeo Ghana is at the confluence of Gambhir and Banganga rivers. Kolleru Lake lies between Krishna and Godavari deltas, fed by Budameru and Tammileru streams.',
    revisionRequired: true,
    createdAt: '2026-09-11'
  },
  {
    id: 'pyq-3',
    year: 2024,
    exam: 'Prelims',
    subject: 'History & Indian Culture',
    topic: 'Sangam Literature & Ports',
    question: 'With reference to ancient South India, Korkai, Poompuhar and Muchiri were well known as: (A) Capital cities (B) Ports (C) Centers of iron and steel making (D) Shrines of Jain Tirthankaras',
    attempted: true,
    correct: true,
    explanation: 'Korkai (Pandya port famous for pearl fishery), Poompuhar/Kaveripattinam (Chola port), and Muchiri/Muziris (Chera port) were celebrated ancient trading ports.',
    revisionRequired: false,
    createdAt: '2026-09-12'
  },
  {
    id: 'pyq-4',
    year: 2023,
    exam: 'Mains',
    subject: 'Indian Polity & Constitution',
    topic: 'Basic Structure Doctrine',
    question: 'The Basic Structure Doctrine has prevented India from descending into constitutional authoritarianism while retaining the democratic spirit of the Constitution. Critically examine. (15 Marks, 250 Words)',
    attempted: true,
    correct: true,
    explanation: 'Explored evolution from Shankari Prasad, Golaknath to Kesavananda, Minerva Mills, and NJAC judgment.',
    revisionRequired: false,
    createdAt: '2026-09-13'
  }
];

export const DEFAULT_MCQS: MCQEntry[] = [
  {
    id: 'mcq-1',
    date: '2026-09-16',
    subject: 'Indian Polity & Constitution',
    topic: 'Fundamental Rights & Writs',
    totalQuestions: 25,
    correct: 21,
    wrong: 3,
    skipped: 1,
    accuracy: 84.0,
    source: 'PW Daily Practice Sheet + Vision Prelims Module',
    notes: 'Stumbled on Habeas Corpus against private individuals vs Mandamus against President.'
  },
  {
    id: 'mcq-2',
    date: '2026-09-15',
    subject: 'History & Indian Culture',
    topic: 'Modern India 1857-1905',
    totalQuestions: 30,
    correct: 24,
    wrong: 5,
    skipped: 1,
    accuracy: 80.0,
    source: 'Spectrum Chapter Review MCQs',
    notes: 'Need clearer timeline review for Vernacular Press Act 1878 and Ilbert Bill 1883.'
  },
  {
    id: 'mcq-3',
    date: '2026-09-14',
    subject: 'Geography & Environment',
    topic: 'Atmosphere & World Climatic Zones',
    totalQuestions: 20,
    correct: 16,
    wrong: 4,
    skipped: 0,
    accuracy: 80.0,
    source: 'PW Geography Drill',
    notes: 'Mediterranean climate precipitation in winter vs summer trade winds.'
  },
  {
    id: 'mcq-4',
    date: '2026-09-13',
    subject: 'Indian Economy & Development',
    topic: 'Banking, RBI & Inflation Indices',
    totalQuestions: 40,
    correct: 33,
    wrong: 5,
    skipped: 2,
    accuracy: 82.5,
    source: 'ForumIAS Prelims Marathon',
    notes: 'Excellent grasp on WPI vs CPI components and service sector exclusion.'
  }
];

export const DEFAULT_TESTS: TestEntry[] = [
  {
    id: 'test-1',
    testName: 'PW UPSC Prelims Sectional Test #01 — Polity & Governance',
    date: '2026-09-13',
    subject: 'Indian Polity & Constitution',
    testType: 'Sectional',
    totalQuestions: 50,
    attempted: 46,
    correct: 38,
    wrong: 8,
    score: 70.66,
    maxScore: 100.0,
    percentage: 70.66,
    timeTakenMinutes: 60,
    mistakes: 'Misread question #14 regarding Governor ordinance powers compared to President Art 123.',
    improvementNotes: 'Always underline "Which of the following is NOT correct" carefully before bubbling!'
  },
  {
    id: 'test-2',
    testName: 'Modern History Sectional Mock #02',
    date: '2026-09-06',
    subject: 'History & Indian Culture',
    testType: 'Sectional',
    totalQuestions: 50,
    attempted: 44,
    correct: 35,
    wrong: 9,
    score: 64.0,
    maxScore: 100.0,
    percentage: 64.0,
    timeTakenMinutes: 58,
    mistakes: 'Confusion between Surat Split factions and Home Rule League branches of Tilak vs Besant.',
    improvementNotes: 'Create chronological timeline flashcards for 1905 to 1920.'
  }
];

export const DEFAULT_ANSWERS: AnswerWritingEntry[] = [
  {
    id: 'ans-1',
    date: '2026-09-15',
    question: 'Discuss the relevance of Gandhian principles of Trusteeship and Sarvodaya in addressing contemporary socio-economic inequalities in India.',
    subject: 'Ethics, Integrity & Aptitude',
    topic: 'Gandhian Ethics & Social Responsibility',
    wordLimit: 150,
    wordsWritten: 148,
    timeTakenMinutes: 8.5,
    selfScore: 6.5,
    maxScore: 10.0,
    modelAnswerReviewed: true,
    improvementNotes: 'Good introduction with CSR under Companies Act 2013 example. Could have added a flowchart connecting Antyodaya to Sarvodaya.'
  },
  {
    id: 'ans-2',
    date: '2026-09-13',
    question: 'Analyze how the constitutional mechanism of Judicial Review balances parliamentary sovereignty in the Indian democratic architecture.',
    subject: 'Indian Polity & Constitution',
    topic: 'Judicial Review & Separation of Powers',
    wordLimit: 250,
    wordsWritten: 242,
    timeTakenMinutes: 13.0,
    selfScore: 10.0,
    maxScore: 15.0,
    modelAnswerReviewed: true,
    improvementNotes: 'Strong citations: Art 13, 32, 136, 226, and Supreme Court Advocates-on-Record case.'
  }
];

export const DEFAULT_DIARY_ENTRIES: DiaryEntry[] = [
  {
    id: 'diary-1',
    date: '2026-09-16',
    whatILearned: 'Polity Article 14 से 18 तक के substantive dimensions को गहराई से समझा। Reasonable classification और arbitrariness के बीच का फर्क अब crystal clear है। The Hindu में IMEC कॉरिडोर का geopolitical perspective नोट किया।',
    whatICompleted: 'सुबह का 1.5 घंटे का deep study slot 100% पूरा किया। लक्ष्मीकांत के 28 पन्नों के micro-notes बनाए और 25 MCQs solve किए।',
    mistakesMade: 'दोपहर में ऑफिस के काम के बाद 15 मिनट सोशल मीडिया स्क्रॉलिंग में चले गए। फोन को study hours में strictly Do-Not-Disturb पर रखना है।',
    howToImproveTomorrow: 'कल सुबह 5:00 बजे अलार्म बजते ही बिना स्नूज़ किए उठना है। Modern History के 1857 Revolt के tribal uprisings को finish करना है।',
    biggestAchievement: 'ऑफिस का पूरा 9 घंटे का काम भी ईमानदारी से किया और 5.5 घंटे का study target भी पूरा हो रहा है! Streak बरकरार है।',
    todaysLesson: 'जब इरादा फौलादी हो तो समय खुद-ब-खुद निकल आता है। थकान मन की कमजोरी है, आत्मा की नहीं।',
    mood: 'Determined',
    overallRating: 5,
    createdAt: '2026-09-16T22:30:00Z',
    updatedAt: '2026-09-16T22:30:00Z'
  },
  {
    id: 'diary-2',
    date: '2026-09-15',
    whatILearned: 'Modern India में Brahmo Samaj और Arya Samaj के सामाजिक-धार्मिक सुधार। कैसे 19वीं सदी के जागरण ने स्वतंत्रता आंदोलन की नींव रखी।',
    whatICompleted: 'PW Live Class और Recorded Class दोनों पूरी की। 1 Mains Answer 8.5 मिनट में लिखा।',
    mistakesMade: 'शाम की PW Live Class से पहले थोड़ा सिरदर्द था क्योंकि पानी कम पिया था।',
    howToImproveTomorrow: 'कम से कम 3 लीटर पानी और दिन में 15 मिनट का stretch जरूर शामिल करना है।',
    biggestAchievement: 'Mains Answer Writing में 6.5/10 का self-score मिला और मॉडल आंसर के major keywords match हुए।',
    todaysLesson: 'कंसिस्टेंसी ही सफलता की चाबी है। हर रोज़ का 1% सुधार 3 साल में 1000 गुना बदलाव लाएगा।',
    mood: 'Focused',
    overallRating: 4,
    createdAt: '2026-09-15T22:30:00Z',
    updatedAt: '2026-09-15T22:30:00Z'
  }
];
